name: CI
on:
  push:
    branches:
      - main
      - fix/ci
  pull_request:
    branches:
      - main
jobs:
  all-cli-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '18.12'
      - run: mv .env.example .env
      - run: npm install
      - run: npm build
      - run: npm test
      - run: npm lint
      - run: npm check-format
      - run: npm check-types
